/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeumemory;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author pp541251
 */
public class InitDlg extends javax.swing.JDialog {

    /**
     * Creates new form InitDlg
     */
    private LesJoueurs lj; // les joueurs sélectionnés
    private boolean ok; // indicateur de fermeture
    private int nc; // niveau du jeu (4,10,18,32)
    
    //constructeur
    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);//appel du constructeur de la classe parent
        initComponents();//on construit l'interface
        this.lj=new LesJoueurs();//On crée une liste de joueur
        ok=false;
        jRadioButton1.setSelected(true);//on sélectionne le bouton de difficulté 4 pardéfaut
        this.nc=4;// on met pardefaut a la difficulté 4
        
    }
    //getter et setter
    public LesJoueurs getJoueurs() {
        return this.lj;
    }
    public boolean getOk() { 
        return this.ok;
    }
    public int getNiveau() {
        return this.nc;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CaseLara = new javax.swing.JCheckBox();
        CaseJack = new javax.swing.JCheckBox();
        CaseJS = new javax.swing.JCheckBox();
        CaseAma = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Choisissez la taille du jeu");
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("enfant(4 personnages,2 familles)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("débutant(10 personnages, 2familles)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("avancé(18 personnages, 4 familles)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("expert(32 personnages, 6 familles)");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton4);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Choisissez les joueurs créé pardefaut");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(4, 1));

        CaseLara.setText("Lara");
        CaseLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseLaraActionPerformed(evt);
            }
        });
        jPanel6.add(CaseLara);

        CaseJack.setText("Jack");
        CaseJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJackActionPerformed(evt);
            }
        });
        jPanel6.add(CaseJack);

        CaseJS.setText("Jean-Sébastien");
        CaseJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJSActionPerformed(evt);
            }
        });
        jPanel6.add(CaseJS);

        CaseAma.setText("Amadeus");
        CaseAma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseAmaActionPerformed(evt);
            }
        });
        jPanel6.add(CaseAma);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel7.add(jScrollPane1);
        jPanel7.add(BPhoto);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel2.add(Valider);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // On met la difficulté à enfant donc 4 persos
        this.nc=4;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // On met la difficulté à debutant donc 10 persos
        this.nc=10;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // On met la difficulté à avancé donc 18 persos
        this.nc=18;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // On met la difficulté à expert donc 32 persos
        this.nc=32;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // Quand on clique sur valider  on va juste crée les personnages que l'on a selectionné et les ajouter a la liste des joueurs
        //en leur donnant un nom une categorie et une image que l'on va chercher dans le dossier
        //le isSelected permet de voir si une case est cochée.
        if(CaseLara.isSelected()){
        Joueur j=new Joueur("Lara", "epiques");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/lara.jpg")).getImage());
        lj.ajouteJoueur(j);
        
        }
        if(CaseJack.isSelected()){
        Joueur j=new Joueur("Jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/jack.png")).getImage());
        lj.ajouteJoueur(j);
        }
        if(CaseJS.isSelected()){
        Joueur j=new Joueur("Jean-Sébastien", "alpins-femmes");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/bach.jpg")).getImage());
        lj.ajouteJoueur(j);
        }
        
        if(CaseAma.isSelected()){
        Joueur j=new Joueur("Amadeus", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/mozart.jpg")).getImage());
        lj.ajouteJoueur(j);
        }
        this.ok=true;
        this.dispose();//On ferme la fenêtre
    }//GEN-LAST:event_ValiderActionPerformed

    private void CaseLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseLaraActionPerformed
        // Quand la case est cochée on crée le joueur 
        //On affiche son image sur le bouton et ses informations dans la zone d'édition en appelant la methode toString
        //qui recupere les infos du joueur
        if(CaseLara.isSelected()){
        Joueur j=new Joueur("Lara", "epiques");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/lara.jpg")).getImage());
        Edition.setText(j.toString());
        Image img = j.getPhoto().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// permet d'adapter l'image au bouton
        BPhoto.setIcon(new ImageIcon(img));
        
        }
        
    }//GEN-LAST:event_CaseLaraActionPerformed

    private void CaseJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJackActionPerformed
        // Quand la case est cochée on crée le joueur 
        //On affiche son image sur le bouton et ses informations dans la zone d'édition en appelant la methode toString
        //qui recupere les infos du joueur
        if(CaseJack.isSelected()){
        Joueur j=new Joueur("Jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/jack.png")).getImage());
        Edition.setText(j.toString());
        Image img = j.getPhoto().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// permet d'adapter l'image au bouton
        BPhoto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_CaseJackActionPerformed

    private void CaseJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJSActionPerformed
        // Quand la case est cochée on crée le joueur 
        //On affiche son image sur le bouton et ses informations dans la zone d'édition en appelant la methode toString
        //qui recupere les infos du joueur
        if(CaseJS.isSelected()){
        Joueur j=new Joueur("Jean-Sébastien", "alpins-femmes");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/bach.jpg")).getImage());
        Edition.setText(j.toString());
        Image img = j.getPhoto().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// permet d'adapter l'image au bouton
        BPhoto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_CaseJSActionPerformed

    private void CaseAmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseAmaActionPerformed
        // Quand la case est cochée on crée le joueur 
        //On affiche son image sur le bouton et ses informations dans la zone d'édition en appelant la methode toString
        //qui recupere les infos du joueur
        if(CaseAma.isSelected()){
        Joueur j=new Joueur("Amadeus", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("/jeumemory/img/mozart.jpg")).getImage());
        Edition.setText(j.toString());
        Image img = j.getPhoto().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// permet d'adapter l'image au bouton
        BPhoto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_CaseAmaActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // Ferme juste la fenêtre
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton BPhoto;
    private javax.swing.JCheckBox CaseAma;
    private javax.swing.JCheckBox CaseJS;
    private javax.swing.JCheckBox CaseJack;
    private javax.swing.JCheckBox CaseLara;
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Valider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
