/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeumemory;

/**
 *
 * @author pp541251
 */

public class PlateauJeu extends javax.swing.JDialog {

    private int tab[][]; //on cree un tableau pur les indice du perso
    private int nbp;//nombre de personnages sur le plateau qui diminue au cours du jeu
    private int nblig;//nombre de ligne du tableau
    private int nbcol;//nombre de colone du tableau
    
    
    public PlateauJeu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public PlateauJeu(int n){
        this.nbp=n;//on initialise le nombres de perso avec n
        this.nblig=(int)(Math.sqrt(nbp*2));//On fait le calcul pour avoir le nombre dligne par rapport au nombre de joueru que l'on a
        this.nbcol=nbp*2/nblig;//Le calcul nous donne le nombre de colone par raport au nombre de joueur et de ligne
        this.tab=new int[this.nblig][this.nbcol];//on cree le tableau avec le nombre de colone et de ligne
        initPlateauJeu();
    }
    //constructeur par defaut
     public PlateauJeu(){
         this(4);//on appel le constructeur standar et on initialise pardefaut avec 4 personnages
    
    }
//getter 
    public int getNbp() {
        return nbp;
    }

    public int getNblig() {
        return nblig;
    }

    public int getNbcol() {
        return nbcol;
    }
    public int getCase(int l,int c){
        return tab[l][c];//permet de voir ce qu'il y a dans une case precise
    }
    public int getNbc(){
        return this.nblig*this.nbcol/2; // retourne le nombre de case que l'on a
    }
    
    public void initPlateauJeu()
    {    //Permet initialiser le plateau de jeu 
            //et de disposer les cartes dessu et on pelle melange pour melanger les carte
        int k=0;
        for(int i=0; i<this.nblig; i++)
        for(int j=0; j<this.nbcol; j++)
        tab[i][j]=(k++)%this.nbp;
        melange();
    }
    public void invalide(int l1, int c1, int l2, int c2)
    {        //on invalide des emplacements du tableau avec -1 car 0 est deja utilisé
    
        tab[l1][c1]=-1;
        tab[l2][c2]=-1;
        nbp--;
    }
    
    public void melange()
    { //SIMULE LE MELANGE DES CARTES EN EFFECTUANT 1000 PERMUTATION 2 A 2
        for(int i=1;i<1000;i++){
            int l1=(int)Math.random()*nblig;
            int c1=(int)Math.random()*nbcol;
            int l2=(int)Math.random()*nblig;
            int c2=(int)Math.random()*nbcol;
            int temp= tab[l1][c1];
            tab[l1][c1]=tab[l2][c2];  // on echange tab1 et tab2 avec une variable intermediaire
            tab[l2][c2]=temp;

           }
    }
    public boolean jeuVide()//teste si il reste  ou nan des cartes sur le plateau de jeu
    { 
        boolean ok=true;
        for(int i=0;i<nblig;i++){
            for(int j=0;j<nbcol;j++){
                if(estValide(i,j))
                    ok=false;
            }
        }
        return ok;
    }
    public boolean estValide(int l, int c)//Teste si une case est Valide c'est a dire a une carte
    { 
        if(tab[l][c]!=-1)
            return true;
        else return false;
    }
    public void termineJeu()//invalides toutes les case du jeu en mettant -1 dans chaque case
    { 
        for(int i=0;i<nblig;i++){
            for(int j=0;j<nbcol;j++)
                tab[i][j]=-1;
        }
        nbp=0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Afficher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Afficher.setText("Afficher");
        getContentPane().add(Afficher, java.awt.BorderLayout.SOUTH);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        jLabel1.setText("Choisissez un joueur pour voir ses caractériqtiques");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlateauJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlateauJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlateauJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlateauJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlateauJeu dialog = new PlateauJeu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
