/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeumemory;

import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author pp541251
 */
public class VisuJoueurDlg extends javax.swing.JDialog {

    //Attribut
    private LesJoueurs lj;//On va afficher une liste de Joueur

    //Constructeur
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, LesJoueurs lesj) {//initialisation des attributs
        super(parent, modal);//On appelle le constructeur de la classe parent
        initComponents();//on créé l'interface
        //lesj.ajouteJoueur(new Joueur());
        this.lj = lesj;//on ajoute a notre liste de joueurs les joueur passés en paramètre
        iniTrombi();//appelle de la méthode de création des boutons

    }

    public void iniTrombi() {//creation des boutons
        int nb = this.lj.getNbJoueurs();//on fixe la longueur du panneau
        Panneau.setLayout(new GridLayout(1, nb));
        for (int i = 0; i < nb; i++) {
            JButton jb = new JButton();
            Joueur j = lj.getJoueur(i);
            jb.setName("" + i);//on fixe un numero comme nom
            jb.addActionListener(new java.awt.event.ActionListener() {//on clonne le bouton a un ecouteur cliquable
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AfficheInfosJoueur(evt);//gestionaire executer quand on clique sur un bouton
                    //elle permet d'afficher les infos du joueur dans la zone d'édition
                }
            }
            );
            Panneau.add(jb);
        }
        this.pack();
    }

    public void AfficheTrombi() {
        for (int i = 0; i < this.lj.getNbJoueurs(); i++) {//on parcours notre liste de joueurs et pour chaque joueur 
            //on lui met une image 
            JButton jp = (JButton) Panneau.getComponent(i);
            Joueur j = this.lj.getJoueur(i);
            //jp.setIcon(new ImageIcon(j.getPhoto()));
            Image img = j.getPhoto().getScaledInstance(jp.getWidth(), jp.getHeight(), Image.SCALE_DEFAULT);//on ajuste l'image au bouton
            jp.setIcon(new ImageIcon(img));//on met l'image sur le bouton

        }
    }

    private void AfficheInfosJoueur(java.awt.event.ActionEvent evt) {
        //Methode qui contient les information du joueur et va les afficher dans la zone d'Edition quand on cliquera sur un bouton de joueur
        String name = ((JButton) evt.getSource()).getName();
        int id = Integer.valueOf(name);

        Edition.setText("Joueur :" + this.lj.getJoueur(id).getPseudo() + "\n");
        Edition.append("Famille préférée :" + this.lj.getJoueur(id).getFamillepref() + "\n");
        Edition.append("en possession des personnages :" + "\n");
        Edition.append("Score :" + this.lj.getJoueur(id).getScore() + "\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panneau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisir un Joueur");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jPanel1.add(Panneau, java.awt.BorderLayout.CENTER);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        jPanel3.add(Afficher);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        AfficheTrombi();
    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true, new LesJoueurs());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
